// Card model. A card is a markdown file; its column is the folder it sits in.
// Nothing is duplicated into a database — the filesystem is the source of truth.

import { readdirSync, readFileSync, writeFileSync, appendFileSync, statSync, existsSync, mkdirSync } from 'node:fs'
import { renameSync } from './fs-retry.mjs'
import { join, basename, resolve, dirname, extname } from 'node:path'
import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import { recoveryTransition } from './recovery.mjs'
import { auditArchiveError } from './audit-routing.mjs'
import { appendHistory, writeCurrentFeedback, historyPath, projectConstraints, lastTransition } from './card-history.mjs'
import { CARD_ID, nextCardId } from './ids.mjs'

const TEMPLATE = new URL('../TASK-TEMPLATE.md', import.meta.url)
const AUDIT_TEMPLATES = {
  seo: new URL('../AUDIT-TEMPLATES/SEO.md', import.meta.url),
  contrast: new URL('../AUDIT-TEMPLATES/CONTRAST.md', import.meta.url),
  design: new URL('../AUDIT-TEMPLATES/DESIGN.md', import.meta.url),
  general: new URL('../AUDIT-TEMPLATES/GENERAL.md', import.meta.url),
}
export const AUDITS = Object.keys(AUDIT_TEMPLATES)

// `workspace` (absolute) is passed only at a Planner handoff, so cards already
// queued or working are never blocked retroactively by the plan check.
export function validatePlan(text, { requireReadiness = false, workspace: planRoot = null, sharedFiles = [] } = {}) {
  const section = (name) => (text.match(new RegExp(`^## ${name}\\s*\\r?\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, 'm'))?.[1] ?? '').replace(/<!--[\s\S]*?-->/g, '').replace(/^\*\*Callers checked:\*\*\s*$/gm, '').trim()
  const workspace = text.match(/^\*\*Workspace:\*\*\s*([^\n]+)$/im)?.[1]?.trim() || '.'
  const readinessLine = text.match(/^\*\*Plan readiness:\*\*[^\n]*$/im)?.[0]
  const readiness = text.match(/^\*\*Plan readiness:\*\*\s*(build-ready|investigation)\s*$/im)?.[1]?.toLowerCase()
  if (requireReadiness && !readinessLine) throw new Error('Plan incomplete: authenticated Planner handoff requires **Plan readiness:** build-ready or investigation')
  if (readinessLine && !readiness) throw new Error('Plan incomplete: Plan readiness must be build-ready or investigation')
  if (/^[A-Za-z]:|^\/|(^|\/)\.\.(\/|$)/.test(workspace.replace(/\\/g, '/'))) {
    throw new Error('Plan incomplete: Workspace must be a project-relative path')
  }
  for (const name of ['Approved brief', 'Files', 'Implementation plan', 'Acceptance criteria']) {
    if (!section(name)) throw new Error(`Plan incomplete: fill ## ${name} before handoff; keep the template headings`)
  }
  if (/^\*\*Workflow version:\*\* 2$/m.test(text)) {
    const criteria = [...section('Acceptance criteria').matchAll(/^-\s+(AC\d+):\s+\S.+$/gm)].map(m => m[1])
    const checks = section('Outcome checks')
    // A cell may hold an escaped pipe, \|, as Markdown allows (Tradeflow TF121).
    const cell = String.raw`(?:\\.|[^|\\])+`
    const unmapped = criteria.find(id => !new RegExp(String.raw`^\s*\|?\s*${id}\s*\|${cell}\|${cell}\|${cell}\|?\s*$`, 'm').test(checks))
    if (!criteria.length || new Set(criteria).size !== criteria.length || unmapped) throw new Error(`Plan incomplete: map each AC ID to change, acceptance check and negative check under Outcome checks${unmapped ? ` (no 4-column row for ${unmapped})` : ''}`)
    if (!section('Prerequisites')) throw new Error('Plan incomplete: state workspace prerequisites (or explicitly none)')
  }
  const fileLines = [...section('Files').matchAll(/^-\s+`([^`]+)`([^\n]*)/gm)]
  const files = fileLines.map(m => m[1])
  // A glob is allowed only for files generated by a script this card also lists (Injectbuddy I302).
  const generator = (rest) => rest.match(/generated by\s+`?([^`\s]+)`?/i)?.[1]
  const unmarked = fileLines.find(([, p, rest]) => isGlob(p) && !generator(rest))
  // I528: the generic message below read as "no globs at all", so a Planner with a valid generated set gave up.
  if (unmarked) throw new Error(`Plan incomplete: ## Files glob ${unmarked[1]} needs the exact words generated by \`<script>\` on its line (e.g. - \`public/legacy/*/index.html\` — generated by \`scripts/x.mjs\`), with that script listed as its own bullet. Other globs are refused.`)
  // I530: name the path that failed; the old message blamed globs for a .py bullet.
  const bad = fileLines.find(([, p]) => /[\\:?<>]|(^|\/)\.\.(\/|$)|^\//.test(p) || !/\.(tsx?|jsx?|mjs|cjs|css|json|md|html?|txt|xml|svg|ya?ml|sql|py|sh|ps1)$/.test(p) && !(readiness === 'investigation' && p.endsWith('/')))
  if (!files.length || bad) {
    throw new Error(`Plan incomplete: ## Files needs exact relative file paths as - \`path/to/file.css\` bullets${bad ? `; ${bad[1]} is not one (no placeholders, folders, absolute or ../ paths, or unknown file types)` : ''}`)
  }
  for (const [, p, rest] of fileLines) {
    const script = isGlob(p) && generator(rest)
    if (script && !files.some(f => !isGlob(f) && f.replace(/^\.\//, '') === script.replace(/^\.\//, ''))) throw new Error(`Plan incomplete: ## Files glob ${p} is generated by ${script}, but ${script} is not listed in ## Files. List the script as its own bullet.`)
  }
  if (/^\*\*Trivial:\*\*\s*yes\s*$/im.test(text) && files.length > 2) {
    throw new Error('Trivial cards may list no more than two files')
  }
  // A card that edits many files is several cards: Injectbuddy I191 (33 files) spent 14.5M
  // tokens across Planner loops and locked files the whole queue waited on (operator, 2026-09-26).
  const editedFiles = section('Files').split(/\r?\n/).filter(line => /^-\s+`[^`]+`/.test(line) && !REFERENCE_ONLY.test(line)).map(line => line.match(/`([^`]+)`/)[1])
  const edited = editedFiles.length
  if (planRoot && edited > MAX_PLAN_FILES) throw new Error(`Plan too wide: ${edited} files to edit (limit ${MAX_PLAN_FILES}). Don't hand this off as one card. If the files are generated by one script, list the script plus one glob line marked 'generated by <script>' (- \`path/*/file.html\` — generated by \`scripts/x.mjs\`), which counts as one file. Otherwise split it: hkb split <card-id> "1. <smaller card: its outcome and files> 2. ..." so the project's orchestrator re-cards each part.`)
  if (readiness === 'investigation') {
    const plan = section('Implementation plan').replaceAll('**', '')
    if (!/(?:check|measurement)\s*(?:commands?|method)?\s*:\s*\S|setup\/start\/check commands?[^\n]*\n[\s\S]*?```/i.test(plan) || !/(?:expected result|disposition)\s*:\s*\S/i.test(plan) || !/stop rules?\s*:\s*\S/i.test(plan)) {
      throw new Error('Plan incomplete: investigation needs a measurement/check, expected result or disposition, and stop rules')
    }
    // Checked last: only the operator can add this marker, so a plan failing on it
    // alone is waiting for the operator, not for more planning (T-148).
    if (!/^\*\*Investigation approved:\*\* yes\s*$/im.test(text.split(/^## Approved brief/m)[0])) throw Object.assign(new Error('Plan incomplete: investigation requires explicit approval on the card'), { operatorApproval: true })
  }
  if (readiness === 'build-ready') {
    const plan = section('Implementation plan')
    const required = [
      ['agreed outcome', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?(?:outcome|agreed outcome)[ \t]*:[ \t]*[^\r\n]+/im],
      ['unchanged constraints', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?unchanged constraints?[ \t]*:[ \t]*[^\r\n]+/im],
      ['observed cause and evidence', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?(?:observed cause|cause)[ \t]*:[ \t]*[^\r\n]+[\s\S]*?(?:^|\n)[ \t]*evidence[ \t]*:[ \t]*[^\r\n]+/im],
      ['inspected current revision/state', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?inspected current (?:revision\/state|revision|state)[ \t]*:[ \t]*[^\r\n]+/im],
      ['concrete changes', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?(?:change|changes|concrete changes)[ \t]*:[ \t]*[^\r\n]+/im],
      ['runnable check and expected result', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?(?:check|check command|setup)[ \t]*:[ \t]*[^\r\n]+[\s\S]*?(?:^|\n)[ \t]*(?:expected(?: result)?|result)[ \t]*:[ \t]*[^\r\n]+/im],
      ['scope/stop rules', /(?:^|\n)[ \t]*(?:[-*][ \t]*)?(?:scope|stop rules?)[ \t]*:[ \t]*[^\r\n]+/im],
    ]
    const missing = required.filter(([, pattern]) => !pattern.test(plan)).map(([name]) => name)
    // Say the exact form: a Claude Haiku Planner wrote "### Observed cause" headings and retried
    // the same shape ten times before escalating (Injectbuddy I260, 2026-09-26).
    if (missing.length) throw new Error(`Plan incomplete: build-ready plan needs ${missing.join(', ')}. Inside ## Implementation plan, write each as a line that starts with its label and a colon (headings do not count): "Agreed outcome: ...", "Unchanged constraints: ...", "Cause: ..." then "Evidence: ...", "Inspected current state: ...", "Changes: ...", "Check: ..." then "Expected result: ...", "Scope: ...".`)
    const cause = plan.match(/(?:^|\n)\s*(?:[-*]\s*)?(?:observed cause|cause)\s*:\s*([^\n]+)/i)?.[1] || ''
    if (/\b(?:unknown|unclear|tbd|todo|investigate)\b/i.test(cause)) throw new Error('Plan incomplete: unknown cause is investigation, not build-ready')
    if ([...section('Files').matchAll(/^[-*]\s+`[^`]+`\s*$/gm)].length) throw new Error('Plan incomplete: each build-ready file needs a concrete target/purpose')
  }
  if (planRoot) {
    // Card checkouts share the integration node_modules through a junction, so an install
    // there rewrote the shared copy under running Builders (throughput audit 2026-09-26 F3).
    const steps = `${section('Prerequisites')}\n${section('Implementation plan')}`.split(/\r?\n/).filter(line => !/\b(?:do not|don't|never|no|avoid|without)\b/i.test(line)).join('\n')
    const install = steps.match(/\b(?:npm (?:ci|install|i)|pnpm (?:install|i)|yarn install)\b/i)?.[0]
    if (install && !editedFiles.some(f => /(^|\/)(package\.json|package-lock\.json|npm-shrinkwrap\.json|pnpm-lock\.yaml)$/.test(f))) throw new Error(`Plan check failed: the plan runs \`${install}\`, but card checkouts share the integration node_modules through a junction, and installing there rewrites it under running Builders. Remove the install step (dependencies are already installed), or list package.json or the lockfile in ## Files if this card changes dependencies.`)
    // Shared per-project check scripts (projectSettings.<project>.sharedFiles) were locked by
    // every card that added its own check to them, one card at a time (Injectbuddy
    // scripts/capture-authed.mjs, 15 cards; throughput audit F1).
    const slashed = p => p.replaceAll('\\', '/').replace(/^\.\//, '').toLowerCase()
    const same = (a, b) => a === b || a.endsWith(`/${b}`) || b.endsWith(`/${a}`)
    const about = `${text.match(/^# .*$/m)?.[0] || ''}\n${section('Approved brief')}`.replaceAll('\\', '/').toLowerCase()
    const shared = editedFiles.find(f => sharedFiles.some(s => same(slashed(f), slashed(s))) && !about.includes(slashed(f)) && !about.includes(basename(f).toLowerCase()))
    if (shared) {
      const id = text.match(/^# (\S+)/m)?.[1]?.toLowerCase() || '<card-id>'
      throw new Error(`Plan check failed: ${shared} is shared by every card in this project, and locking it makes the other cards wait. Leave it out of ## Files and write this card's own check as scripts/check-${id}-*.mjs (new), importing what it needs from ${shared}. Only a card whose title or Approved brief names ${shared} may change it.`)
    }
    checkPlanPaths(planRoot, section('Files'), section('Prerequisites'), section('Implementation plan'))
    if (readiness === 'build-ready' && !/^\*\*Callers checked:\*\*[ \t]*\S/m.test(section('Implementation plan'))) throw new Error('Plan check failed: ## Implementation plan needs a **Callers checked:** line listing every file that references each changed function/export (or "none"). Grep for each changed symbol first.')
    // Most Builder kick-backs were plans whose own check did not match the code: a wrong
    // selector (I427), a screenshot count the script never produced (I432), a zero-reference
    // AC that files outside ## Files made impossible (I445). Running the check once first catches them.
    if (readiness === 'build-ready' && !/^\*\*Base check:\*\*[ 	]*\S/m.test(section('Implementation plan'))) throw new Error('Plan check failed: ## Implementation plan needs a **Base check:** line: run the Check once on the current integration checkout and record the command and what it printed (a regression check should fail there; a count, selector or file it relies on must exist). If it cannot run before the change (it tests a file this card creates), say why.')
  }
}

// A card worktree is a checkout of the integration HEAD, so a plan may only rely on
// files git tracks there (T-145/T-148, Kiwitown T-1). Untracked or gitignored files
// (TASKS/, *.md in some projects) exist for the Planner but not for the Builder.
// Checks ## Files and backticked path-shaped words in ## Prerequisites and
// ## Implementation plan, never prose.
function checkPlanPaths(planRoot, filesSection, prereqSection, planSection) {
  const root = planRoot.replaceAll('\\', '/')
  const readOnly = 'cite a file that exists only outside git by absolute path as a read-only reference in ## Prerequisites'
  const tracked = (path) => {
    const git = spawnSync('git', ['-C', planRoot, 'cat-file', '-e', `HEAD:./${path.replace(/\/+$/, '')}`], { windowsHide: true, encoding: 'utf8' })
    if (git.status === 0) return true
    if (git.status === null || /not a git repository/i.test(git.stderr)) return existsSync(resolve(planRoot, path)) // non-Git workspace
    return false
  }
  const problem = (path) => tracked(path) ? null
    : existsSync(resolve(planRoot, path)) ? `exists in ${root} but is not tracked by git at HEAD (untracked or gitignored), so the card worktree will not have it`
      : `does not exist in ${root}`
  const newFiles = new Set()
  for (const [, path, rest] of filesSection.matchAll(/^[-*]\s+`([^`]+)`([^\n]*)/gm)) {
    if (/\(new\b[^)]*\)/i.test(rest)) { newFiles.add(path); continue }
    if (isGlob(path)) {
      const git = spawnSync('git', ['-C', planRoot, 'ls-files', '--', `:(glob,icase)${path}`], { windowsHide: true, encoding: 'utf8' })
      if (git.status === 0 && !git.stdout.trim()) throw new Error(`Plan check failed: ## Files glob ${path} matches no file tracked by git in ${root}. Fix the glob so it matches the generated files.`)
      continue // non-Git workspace: nothing to check against
    }
    const why = problem(path)
    if (why) throw new Error(`Plan check failed: ## Files path ${path} ${why}. Fix the path, mark a file this card creates with (new), or ${readOnly}.`)
  }
  // Ignored root files such as .env.devtools.local exist only in the integration
  // checkout (Injectbuddy I227/I265); the Builder gets the project's envFile instead.
  const hint = (path) => /(^|\/)\.env/i.test(path)
    ? 'Card checkouts have no ignored .env files: rely on the project\'s approved envFile (board.config.json projectSettings envFile), which the Builder runs with node --env-file="<absolute envFile>"; never copy or test it inside the card checkout'
    : `Mark a file this card creates with (new), or ${readOnly}`
  for (const [name, text] of [['Prerequisites', prereqSection], ['Implementation plan', planSection]]) {
    for (const [, span, rest] of text.matchAll(/`([^`]+)`([^\n`]*)/g)) {
      if (/^\s*\(new\b/i.test(rest)) continue
      const single = !/\s/.test(span.trim())
      for (const word of span.trim().split(/\s+/)) {
        const token = word.split('=').pop().replace(/^["'(]+|["'),;]+$/g, '').replaceAll('\\', '/').replace(/^\.\//, '')
        if (/^[A-Za-z]:\//.test(token)) {
          if (single && name === 'Prerequisites' && !existsSync(token)) throw new Error(`Plan check failed: ## Prerequisites path ${token} does not exist. Remove it or cite a file that exists.`)
          continue
        }
        // Relative file paths only (a/b.ext, .env.local), not URLs, globs or node_modules (junctioned in).
        if (!/^[\w@.[\]-]+(?:\/[\w@.[\]-]+)*\.[\w-]{1,20}$/.test(token) || /^node_modules\//.test(token) || /(^|\/)\.\.(\/|$)/.test(token) || newFiles.has(token)) continue
        // A lone a/b.ext prerequisite must exist and be tracked. Anything else (root-level
        // names, command arguments, plan steps) is refused only when it is a file the
        // Planner can see that the card worktree will not have.
        const why = single && name === 'Prerequisites' && token.includes('/') ? problem(token)
          : statSync(resolve(planRoot, token), { throwIfNoEntry: false })?.isFile() ? problem(token) : null
        if (why) throw new Error(`Plan check failed: ## ${name} path ${token} ${why}. ${hint(token)}.`)
      }
    }
  }
}

// A complete plan held only by an operator-only marker. The board asks the operator
// once (Owner) instead of re-prompting a Planner that cannot add the marker.
export function awaitsOperatorApproval(text) {
  try { validatePlan(text) } catch (error) { return !!error.operatorApproval }
  return false
}
export const approvalQuestion = (id) => `Approve the investigation for ${id}? The plan is ready, but only you can approve it: add the line \`**Investigation approved:** yes\` above ## Approved brief, then drag the card back to Planning. Or edit or cancel the card.`
export function askForApproval(tasksDir, card) {
  const moved = moveCard(tasksDir, card.id, 'owner')
  writeCurrentFeedback(tasksDir, moved, 'Needs you', approvalQuestion(card.id))
  return moved
}

// Column order is board order. `dir` is the folder under <project>/TASKS/.
// `backlog` and `queue` keep their historical names so existing repos need no migration.
export const COLUMNS = [
  // First, because it is the only column the board cannot act on by itself. Only a
  // deliberate board move reaches it; every automatic route stops in Owner, which the
  // Kanban Manager works (2026-09-25: 40 Owner alerts in a day, mostly board problems).
  { key: 'pou',       dir: 'pou',       label: 'Pou'       },
  { key: 'owner',     dir: 'owner',     label: 'Owner'     },
  { key: 'planning',  dir: 'planning',  label: 'Planning'  },
  { key: 'planned',   dir: 'backlog',   label: 'Planned'   },
  { key: 'queue',     dir: 'queue',     label: 'Queue'     },
  { key: 'working',   dir: 'working',   label: 'Working'   },
  // Retired 2026-09-25: nothing moves here (moveCard sends it to Planning). Kept so an old
  // card left in TASKS/issues still shows and can be moved; startup drains it to Planning.
  { key: 'issues',    dir: 'issues',    label: 'Issues'    },
  { key: 'review',    dir: 'review',    label: 'Review'    },
  { key: 'completed', dir: 'completed', label: 'Completed' },
]

// Not a column — a collapsed drawer at the end of the board.
export const ARCHIVE = { key: 'archive', dir: 'archive', label: 'Archive' }

const ALL = [...COLUMNS, ARCHIVE]

export const columnByKey = (key) => ALL.find((c) => c.key === key)

// Files that live in TASKS/ but are not cards.
const NOT_A_CARD = /^(README|TASK-TEMPLATE|PROJECT-CONSTRAINTS|PROJECT-WORKSPACES|TASKLOG|BRIEF)\.md$/i

const HEADING = new RegExp(String.raw`^#\s+(?:(${CARD_ID})\s*[—–-]\s*)?(.+)$`, 'm')
// Legacy T- ids were matched case-insensitively in file names; prefixed ids are
// capitals only, so an ordinary file such as v2-notes.md is never read as an id.
const ID_FROM_NAME = /^([Tt]-\d+|[A-Z]{1,3}\d+(?![A-Za-z0-9]))/
const PRIORITY = /\*\*Priority\*\*\s*(\d+)\s*\/\s*10/i
const STATUS = /\*\*Status:\*\*\s*([^·\n]+)/i
const SURFACE = /\*\*Surface:\*\*\s*([^·\n]+)/i
const CATEGORY = /^\*\*Category:\*\*\s*([^\n]+)$/im
const WORKSPACE = /^\*\*Workspace:\*\*\s*([^\n]+)$/im
const AUDIT = /^\*\*Audit:\*\*\s*([^\n]+)$/im
export const CATEGORIES = ['ui', 'code', 'auth-security', 'data']
// Auto-review lives in the card, not in board state, so the planner can set it
// when it writes the card and a human can see it in the diff.
const AUTOREVIEW = /^\*\*Auto-review:\*\*\s*(yes|no)\s*$/im
const TRIVIAL = /^\*\*Trivial:\*\*\s*(yes|no)\s*$/im
const AGENT_SETTING = /\*\*(Planner|Builder|Reviewer|Trivial)\s+(engine|model|reasoning):\*\*\s*([^\n]+)$/gim
const AGENT_STAGE = { Planner: 'planning', Builder: 'working', Reviewer: 'review', Trivial: 'trivial' }
// Planner-authored time estimates, same metadata line as Priority/Status/Surface.
const EST_BUILD = /\*\*Est build:\*\*\s*(\d+)\s*m/i
const EST_REVIEW = /\*\*Est review:\*\*\s*(\d+)\s*m/i
// Hard gate: a queued card naming a prerequisite is not spawned until that
// prerequisite has landed. See unmetBlockers in autospawn.mjs.
// The (?<!`) excludes a backtick-wrapped mention — a code-style literal used
// to talk ABOUT the field, not set it. Real incident (T-59, 2026-08-11): a
// note explaining "a line like `**Blocked by:** nothing` would be read as an
// unresolvable ID" was itself read as exactly that, self-blocking the card
// with no real field anywhere on it.
const BLOCKED_BY = /(?<!`)\*\*Blocked by:\*\*\s*([^\n]+)/i
const ISSUE_KEY = /(?<!`)\*\*Issue key:\*\*\s*([^\n]+)/i
const MISSION = /(?<!`)\*\*Mission:\*\*\s*([^\n]+)/i
const BUILD_ATTEMPT = /^\*\*Build attempt\*\*/gm
const REVIEW_FEEDBACK = /^\*\*Review feedback\*\*/gm
const RESET_MARKER_LINE = /^\*\*(Build attempt|Review feedback)\*\*/i
// Reviewers date their headings and bullet their verdicts; both forms count (Tradeflow T-35:
// hkb pass refused two PASS reviews written as "## Reviewer evidence — <date>" / "- **Review verdict:** PASS").
const REVIEWER_EVIDENCE_LINE = /^##\s+Reviewer evidence\b.*$/i
const ANY_HEADING_LINE = /^#{1,6}\s+/
const REVIEW_VERDICT_LINE = /^(?:[-*]\s+)?\*\*Review verdict:\*\*\s*(PASS|FAIL|UNKNOWN)\b/i
const FILES_SECTION = /##\s*Files\s*\n([\s\S]*?)(?=\n##\s|\n*$)/i
const FILE_LINE = /^-\s*`([^`]+)`/gm
const DIRTY_SNAPSHOT = /^\*\*Dirty snapshot:\*\*[^\n]*\n+```json\n([\s\S]*?)\n```/gm

// Metadata may follow an assignment override longer than 2KB. Truncating here
// silently loses Workflow/Auto-review and sends corrections down the wrong lane.
function readHead(path) {
  return readFileSync(path, 'utf8')
}

// Agents append their reason to the bottom of the card, so the one line the
// operator actually needs lives in the tail, not the head.
const ASK = /\*\*(Needs you|Kicked back|Spawn failed|Review feedback)\*\*[^\n]*\n+([\s\S]+?)(?=\n+---|\n*$)/g

// How many times a reviewer has sent this card back. Counted from the card itself
// rather than kept in side state, so it survives restarts and is visible in the
// diff — and so the loop cannot be reset by deleting a state file.
const ROUND = /\*\*Review feedback\*\*/g

function readAsk(path, bytes = 8192) {
  const current = readFileSync(path, 'utf8').match(/^## Current feedback\r?\n([^\n]+): ([\s\S]*?)(?=^History entry:|^## |$(?![\s\S]))/m)
  if (current) return { kind: current[1], text: current[2].trim() }
  const buf = readFileSync(path)
  const tail = buf.subarray(Math.max(0, buf.length - bytes)).toString('utf8')
  let last = null
  for (const m of tail.matchAll(ASK)) last = { kind: m[1], text: m[2].trim() }
  return last
}

// Counted over the whole file: rounds accumulate over a card's life, and the
// earliest ones scroll out of any tail window.
function reviewRounds(path) {
  return (readFileSync(path, 'utf8').match(ROUND) || []).length
}

const plain = (s) => (s ?? '').replace(/\*\*|`/g, '').trim()

// First backtick token on each `## Files` bullet line — the file path itself,
// not the descriptive prose (which often has its own backtick-quoted names).
// A line the plan marks unchanged or read-only is context, not a file the card edits,
// so it takes no lock (Tradeflow TF54 waited 7 hours on files it only references).
export const MAX_PLAN_FILES = 15

// A ## Files glob (only for script-generated files): `*` is one path segment, `**` any
// depth. Case-insensitive, since card paths are Windows paths. Every file-scope check
// (plan width, hkb done scope, locks, review grouping) matches through these.
export const isGlob = (path) => path.includes('*')
const globPrefix = (glob) => glob.replaceAll('\\', '/').split('*')[0].toLowerCase()
export function globMatches(glob, path) {
  const segments = glob.replaceAll('\\', '/').split('/')
  const escape = (s) => s.replace(/[.+?^${}()|[\]\\]/g, '\\$&')
  const body = segments.map((s, i) => s === '**' ? (i === segments.length - 1 ? '.*' : '(?:[^/]+/)*')
    : s.split('*').map(escape).join('[^/]*') + (i < segments.length - 1 ? '/' : '')).join('')
  return new RegExp(`^${body}$`, 'i').test(path.replaceAll('\\', '/'))
}
// Two globs conflict when either literal prefix contains the other (conservative).
export function filesOverlap(a, b) {
  if (isGlob(a) && isGlob(b)) { const [pa, pb] = [globPrefix(a), globPrefix(b)]; return pa.startsWith(pb) || pb.startsWith(pa) }
  if (isGlob(a)) return globMatches(a, b)
  if (isGlob(b)) return globMatches(b, a)
  return a === b
}
const REFERENCE_ONLY = /^-\s*`[^`]+`\s*(?:—|–|-|:|\()\s*(?:unchanged|read-only|reference only)\b/i
export function cardFiles(path) {
  const section = readFileSync(path, 'utf8').match(FILES_SECTION)?.[1] ?? ''
  return [...section.matchAll(FILE_LINE)].filter((m) => !REFERENCE_ONLY.test(m[0] + section.slice(m.index + m[0].length).split('\n')[0])).map((m) => m[1].trim())
}

function cardWorkspace(projectPath, card) {
  return resolve(projectPath, card.workspace || '.')
}

function parseGitStatus(output) {
  const records = output.split('\0').filter(Boolean)
  const files = []
  for (let i = 0; i < records.length; i++) {
    const status = records[i].slice(0, 2)
    const path = records[i].slice(3).replace(/\\/g, '/')
    if (!path) continue
    if (status[0] === 'R' || status[0] === 'C') i++
    files.push({ path, status })
  }
  return files
}

function dirtyFiles(workspace, paths = []) {
  const args = ['-C', workspace, 'status', '--porcelain=v1', '-z']
  if (paths.length) args.push('--', ...paths)
  const result = spawnSync('git', args, { encoding: 'utf8', timeout: 30000, windowsHide: true })
  if (result.status !== 0) throw new Error(`git status failed in ${workspace}: ${(result.stderr || result.stdout).trim()}`)
  return parseGitStatus(result.stdout).map((file) => {
    const full = join(workspace, file.path)
    let sha256 = null
    try {
      if (statSync(full).isFile()) sha256 = createHash('sha256').update(readFileSync(full)).digest('hex')
    } catch { /* deleted, mid-write, or a directory: status is enough */ }
    return {
      ...file,
      sha256,
    }
  }).sort((a, b) => a.path.localeCompare(b.path))
}

export function dirtySnapshotForCard(card, projectPath, { listedOnly = false, ignoreTaskState = false } = {}) {
  const workspace = cardWorkspace(projectPath, card)
  const paths = listedOnly ? cardFiles(card.path) : []
  const files = (listedOnly && !paths.length ? [] : dirtyFiles(workspace, paths))
    .filter((f) => !ignoreTaskState || !f.path.startsWith('TASKS/'))
  return { card: card.id, workspace: card.workspace || '.', files }
}

export function appendDirtySnapshot(card, snapshot, now = new Date()) {
  if (!snapshot?.files?.length) return
  appendFileSync(card.path, `\n\n---\n\n**Dirty snapshot:** ${now.toISOString()}\n\n\`\`\`json\n${JSON.stringify(snapshot)}\n\`\`\`\n`)
}

export function latestDirtySnapshot(path) {
  let latest = null
  for (const match of readFileSync(path, 'utf8').matchAll(DIRTY_SNAPSHOT)) {
    try { latest = JSON.parse(match[1]) } catch {}
  }
  return latest
}

export function currentDirtyMatchesSnapshot(card, projectPath) {
  const recorded = latestDirtySnapshot(card.path)
  if (!recorded || recorded.card !== card.id) return false
  const current = dirtySnapshotForCard(card, projectPath, { listedOnly: true, ignoreTaskState: true })
  return JSON.stringify(current) === JSON.stringify(recorded)
}

// A card parse reads the file five times, and readBoard/findCard re-parse every card,
// archive included, many times per poll: 82% of the server's time went to file reads
// and board requests took up to 20s (2026-09-24). Reuse a parse until the file changes.
const parsed = new Map()
export function parseCard(path, columnKey) {
  const stat = statSync(path)
  const hit = parsed.get(path)
  if (hit && hit.mtimeMs === stat.mtimeMs && hit.size === stat.size) return { ...structuredClone(hit.card), column: columnKey }
  const card = parseCardFile(path, columnKey)
  parsed.set(path, { mtimeMs: stat.mtimeMs, size: stat.size, card })
  return structuredClone(card)
}

function parseCardFile(path, columnKey) {
  const file = basename(path)
  const head = readHead(path)
  const text = readFileSync(path, 'utf8')
  const heading = head.match(HEADING)
  const idFromName = file.match(ID_FROM_NAME)

  const agentSettings = {}
  for (const match of text.matchAll(AGENT_SETTING)) {
    const stage = AGENT_STAGE[match[1]], field = match[2].toLowerCase()
    agentSettings[stage] ||= {}
    agentSettings[stage][field] = match[3].trim().toLowerCase()
  }
  return {
    id: (heading?.[1] || idFromName?.[1] || file.replace(/\.md$/i, '')).toUpperCase(),
    title: (heading?.[2] || file.replace(/\.md$/i, '')).trim(),
    file,
    path,
    column: columnKey,
    cardOwned: /^\*\*Workflow:\*\* card-owned$/m.test(head),
    createdAt: head.match(/^\*\*Created:\*\* (.+)$/m)?.[1] || null,
    priority: Number(head.match(PRIORITY)?.[1] ?? 0),
    // The board renders text, not markdown, so bold markers would show as asterisks.
    status: plain(head.match(STATUS)?.[1]),
    surface: plain(head.match(SURFACE)?.[1]),
    category: CATEGORIES.includes(plain(head.match(CATEGORY)?.[1]).toLowerCase())
      ? plain(head.match(CATEGORY)?.[1]).toLowerCase()
      : 'code',
    workspace: plain(head.match(WORKSPACE)?.[1]) || '.',
    audit: AUDITS.includes(plain(head.match(AUDIT)?.[1]).toLowerCase())
      ? plain(head.match(AUDIT)?.[1]).toLowerCase()
      : '',
    autoReview: head.match(AUTOREVIEW)?.[1]?.toLowerCase() === 'yes',
    trivial: head.match(TRIVIAL)?.[1]?.toLowerCase() === 'yes',
    agentSettings,
    estBuild: head.match(EST_BUILD)?.[1] ? Number(head.match(EST_BUILD)[1]) : null,
    estReview: head.match(EST_REVIEW)?.[1] ? Number(head.match(EST_REVIEW)[1]) : null,
    // Only real card IDs count: "**Blocked by:** none. No deployment…" became one
    // unresolvable blocker and held Injectbuddy I228 in Planned (2026-09-25).
    blockedBy: [...new Set((head.match(BLOCKED_BY)?.[1] || '').toUpperCase().match(new RegExp(String.raw`\b${CARD_ID}\b`, 'g')) || [])],
    issueKey: plain(head.match(ISSUE_KEY)?.[1]),
    mission: plain(head.match(MISSION)?.[1]),
    buildAttempts: (text.match(BUILD_ATTEMPT) || []).length,
    reviewPassed: hasCurrentReviewPass(text),
    ask: readAsk(path),
    reviewRounds: reviewRounds(path),
    mtime: statSync(path).mtimeMs,
    // When the card first existed. A column move is a rename, which keeps birthtime
    // on Windows and ext4, so this survives the card's trip across the board — mtime
    // does not, it resets every time an agent appends a note.
    added: statSync(path).birthtimeMs || statSync(path).ctimeMs,
  }
}

export function appendBuildAttempt(card, now = new Date()) {
  appendFileSync(card.path, `\n\n---\n\n**Build attempt** ${now.toISOString()}\n`)
}

export function appendReviewPass(card, note, now = new Date()) {
  appendFileSync(card.path,
    `\n\n---\n\n## Reviewer evidence\n\n${note}\n\n**Review verdict:** PASS ${now.toISOString()}\n`)
}

const realReviewerEvidence = (evidence) =>
  evidence.length > 0 && !/^(todo|tbd|n\/a|template|placeholder|\[.*\])$/i.test(evidence)

export function currentReviewDecision(text) {
  // A pending correction invalidates any verdict retained in old evidence.
  if (/^## Current feedback\r?\nReview feedback:/m.test(text)) {
    const feedbackAt = text.indexOf('## Current feedback')
    const verdictAt = text.lastIndexOf('**Review verdict:**')
    if (verdictAt < feedbackAt) return null
  }
  let inFence = false
  let afterReset = true
  let inReviewerEvidence = false
  let evidence = ''
  let latest = null

  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (/^```/.test(line)) {
      inFence = !inFence
      continue
    }
    if (inFence || line.startsWith('>')) continue
    if (RESET_MARKER_LINE.test(line)) {
      afterReset = true
      inReviewerEvidence = false
      evidence = ''
      latest = null
      continue
    }
    if (REVIEWER_EVIDENCE_LINE.test(line)) {
      inReviewerEvidence = afterReset
      evidence = ''
      continue
    }
    const verdict = line.match(REVIEW_VERDICT_LINE)
    if (verdict && afterReset) {
      latest = { verdict: verdict[1], evidence: evidence.trim() }
      inReviewerEvidence = false
      continue
    }
    if (inReviewerEvidence && ANY_HEADING_LINE.test(line)) {
      inReviewerEvidence = false
      continue
    }
    if (inReviewerEvidence) evidence += `${raw}\n`
  }
  if (!latest || !realReviewerEvidence(latest.evidence)) return null
  return latest
}

export function hasCurrentReviewPass(text) {
  return currentReviewDecision(text)?.verdict === 'PASS'
}

export function hasBuilderPass(card) {
  try {
    const text = readFileSync(card.path, 'utf8')
    const result = ['Implementation', 'Evidence']
      .map((name) => text.match(new RegExp(`^## ${name}\\s*\\r?\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, 'm'))?.[1]?.replace(/<!--[\\s\\S]*?-->/g, '') ?? '')
      .join('\n')
    return builderPassIn(builderResult(result))
  } catch { return false }
}

// Builders also write "- Stage: builder, Outcome: PASS, Files: ..." on one line and
// "Outcome: PASS: <note>"; read those the same (Injectbuddy I556 stalled on the format).
export const BUILDER_FIELDS = ['Stage', 'Outcome', 'Files', 'Check', 'Result', 'Evidence', 'Blocker']
export const builderResult = text => text.replaceAll('**', '').replace(/^[ \t]*[-*][ \t]+/gm, '')
  .replace(new RegExp(`[,;][ \\t]*(?=(?:${BUILDER_FIELDS.join('|')}):)`, 'g'), '\n')
export const builderPassIn = result => /^Stage:\s*builder\s*$/mi.test(result) && /^Outcome:\s*PASS(?:\s*$|\s*[:.;—–-]\s*\S)/mi.test(result)

export function canArchive(card) {
  return (!card.cardOwned && !card.mission) || card.reviewPassed || !!card.audit || hasOperatorCompletion(card) ||
    (card.cardOwned && !card.autoReview && hasBuilderPass(card) && hasIntegratedWorktree(card))
}

function hasIntegratedWorktree(card) {
  try {
    return JSON.parse(readFileSync(join(dirname(dirname(card.path)), '.board-worktrees.json'), 'utf8'))[card.id]?.state === 'integrated'
  } catch { return false }
}

// Explicit human waiver is separate from Review PASS and bound to exact evidence.
export function hasOperatorCompletion(card) {
  try {
    const tasksDir = dirname(dirname(card.path))
    const receipt = JSON.parse(readFileSync(join(tasksDir, '.operator-completions.json'), 'utf8'))[card.id]
    const work = JSON.parse(readFileSync(join(tasksDir, '.board-worktrees.json'), 'utf8'))[card.id]
    const hash = path => createHash('sha256').update(readFileSync(path)).digest('hex')
    return receipt?.kind === 'explicit-user-review-waiver' && !!receipt.authorization && work?.state === 'integrated' && receipt.commit === work.commit && receipt.cardHash === hash(card.path) && receipt.evidenceHash === hash(receipt.evidencePath)
  } catch { return false }
}

// Priority lives in the card's metadata line, same as everything else the board
// reads. Editing it here keeps the file the single source of truth.
export function setPriority(tasksDir, cardId, priority) {
  const n = Math.max(0, Math.min(10, Math.round(Number(priority))))
  if (!Number.isFinite(n)) throw new Error(`priority must be 0-10, got: ${priority}`)

  const card = findCard(tasksDir, cardId)
  const text = readFileSync(card.path, 'utf8')
  const next = withPriority(text, n)
  if (next !== text) writeFileSync(card.path, next)
  return { ...card, priority: n }
}

function withPriority(text, n) {
  const line = `**Priority** ${n}/10`
  if (PRIORITY.test(text)) return text.replace(PRIORITY, line)
  const heading = text.match(HEADING)
  return heading ? text.replace(heading[0], `${heading[0]}\n\n${line}`) : `${line}\n\n${text}`
}

// The header's Blocked-by line sits right under Priority (I270's format). An empty list removes it.
function withBlockers(text, ids) {
  const line = ids.length ? `**Blocked by:** ${ids.join(', ')}` : ''
  if (/^\*\*Blocked by:\*\*/m.test(text)) return text.replace(/^\*\*Blocked by:\*\*[^\r\n]*(\r?\n)?/m, (_, eol) => line && line + (eol || ''))
  if (!line) return text
  const anchor = text.match(/^\*\*Priority\*\*[^\r\n]*/m) || text.match(/^\*\*Trivial:\*\*[^\r\n]*/m) || text.match(HEADING)
  const eol = text.includes('\r\n') ? '\r\n' : '\n'
  return anchor ? text.replace(anchor[0], `${anchor[0]}${eol}${line}`) : `${line}${eol}${eol}${text}`
}

function checkPriority(priority) {
  if (!Number.isInteger(priority) || priority < 1 || priority > 10) throw new Error(`priority must be a whole number from 1 to 10, got: ${JSON.stringify(priority)}`)
}

function cardIds(ids, field) {
  if (!Array.isArray(ids) || ids.some((b) => typeof b !== 'string' || !b.trim())) throw new Error(`${field} must be an array of card IDs`)
  return [...new Set(ids.map((b) => b.trim().toUpperCase()))]
}

// New blockers must be cards in this project (any lane, archive included), not the card itself, and must not close a loop.
function checkBlockers(board, id, ids, field) {
  ids = cardIds(ids, field)
  if (ids.includes(id)) throw new Error(`${id} cannot be blocked by itself`)
  const known = new Set(Object.values(board).flat().map((c) => c.id))
  const unknown = ids.filter((b) => !known.has(b))
  if (unknown.length) throw new Error(`${field} names no card in this project: ${unknown.join(', ')}`)
  if (cycleFor({ id, blockedBy: ids }, board)) throw new Error(`Blocking ${id} on ${ids.join(', ')} would make a dependency cycle`)
  return ids
}

// A dependency cycle among live cards; an archived card has landed, so nothing waits on it.
export function cycleFor(card, board) {
  const byId = new Map()
  for (const c of Object.entries(board).filter(([key]) => key !== 'archive').flatMap(([, cards]) => cards)) {
    if (!byId.has(c.id)) byId.set(c.id, c)
    else byId.set(c.id, null)
  }
  const seen = new Set()
  const visit = (id) => {
    if (id === card.id) return true
    if (seen.has(id)) return false
    seen.add(id)
    const next = byId.get(id)
    return !!next && (next.blockedBy || []).some(visit)
  }
  return (card.blockedBy || []).some(visit)
}

// POST /api/card-update: orchestrators maintain their own cards (priority, blockers,
// dated decision notes) without hand-editing the file. The caller sets `lockBlockers`
// while a live agent holds the card.
export function updateCard(tasksDir, cardId, { priority, addBlockedBy = [], removeBlockedBy = [], note } = {}, { lockBlockers = false, now = new Date() } = {}) {
  const card = findCard(tasksDir, cardId)
  if (card.column === 'archive') throw new Error(`${card.id} is archived; archived cards cannot be updated`)
  let text = readFileSync(card.path, 'utf8')
  const changes = []
  if (priority !== undefined) {
    checkPriority(priority)
    text = withPriority(text, priority)
    changes.push(`priority ${priority}/10`)
  }
  const add = cardIds(addBlockedBy, 'addBlockedBy'), remove = cardIds(removeBlockedBy, 'removeBlockedBy')
  if (add.length || remove.length) {
    if (lockBlockers) throw new Error(`${card.id} has a live agent in ${card.column}; blocker changes are refused until it finishes (note and priority are still allowed)`)
    checkBlockers(readBoard(tasksDir), card.id, add, 'addBlockedBy')
    const next = [...new Set([...card.blockedBy, ...add])].filter((b) => !remove.includes(b))
    text = withBlockers(text, next)
    changes.push(`blocked by ${next.join(', ') || 'nothing'}`)
  }
  if (note !== undefined) {
    const heading = typeof note?.heading === 'string' ? note.heading.trim() : ''
    const body = typeof note?.text === 'string' ? note.text.trim() : ''
    // Board markers (Review feedback, Needs you, Blocked by, ...) in a note would be read as card state.
    if (!/^[A-Za-z][A-Za-z0-9 '-]{0,39}$/.test(heading) || /^(build attempt|review feedback|needs you|kicked back|spawn failed|parked|priority)$/i.test(heading)) throw new Error('note.heading must be a short plain label such as "Decision" or "Operator decision" (letters, digits, spaces; at most 40 characters)')
    if (!body) throw new Error('note.text is required')
    // Board fields are bold labels or headings at the start of a line (`**Blocked by:** ...`,
    // `**Investigation approved:** yes`, `## Files`), plus any `**Label:**`. A glob such as
    // public/legacy/** mid-line is not one (Injectbuddy chat, 2026-09-26).
    if (/^[\s>*-]*\*\*|\*\*[^*\n]+:\*\*|^\s*#/m.test(body)) throw new Error('note.text must be plain text: no line starting with ** bold, no **Label:** field and no # headings (the board reads those as card fields); ** inside a path such as public/legacy/** is fine')
    const eol = text.includes('\r\n') ? '\r\n' : '\n'
    text = `${text.trimEnd()}${eol}${eol}**${heading}** ${now.toISOString()}${eol}${eol}${body.replace(/\r?\n/g, eol)}${eol}`
    changes.push(`note: ${heading}`)
  }
  if (!changes.length) throw new Error('Nothing to update: send priority, addBlockedBy, removeBlockedBy or note')
  writeFileSync(card.path, text)
  appendHistory(tasksDir, card.id, { event: 'card-update', changes })
  return { card: parseCard(card.path, card.column), changes }
}

// Toggle the auto-review marker by rewriting the one line in the card. The card
// stays the source of truth, so the flag survives outside the board entirely.
export function setAutoReview(tasksDir, cardId, on) {
  const card = findCard(tasksDir, cardId)
  const text = readFileSync(card.path, 'utf8')
  const has = AUTOREVIEW.test(text)

  let next
  if (!on) {
    // Off means no marker, not a marker saying no. Toggling on and back off has
    // to leave the card byte-identical, or every toggle dirties someone's diff.
    next = has ? text.replace(/\n*^\*\*Auto-review:\*\*[^\n]*\n/im, '\n') : text
  } else if (has) {
    next = text.replace(AUTOREVIEW, '**Auto-review:** yes')
  } else {
    // Put it directly under the heading, where the other metadata already lives.
    const heading = text.match(HEADING)
    next = heading
      ? text.replace(heading[0], `${heading[0]}\n\n**Auto-review:** yes`)
      : `**Auto-review:** yes\n\n${text}`
  }
  if (next !== text) writeFileSync(card.path, next)
  return { ...card, autoReview: on }
}

// Archive holds most cards and rarely changes, yet every poll re-stats each file
// (most of the board server's CPU, 2026-09-27). Reuse it until a card enters or
// leaves (the folder's mtime changes), or ARCHIVE_TTL_MS passes for in-place edits.
const ARCHIVE_TTL_MS = 30000
const archiveCache = new Map()
function readColumn(tasksDir, col) {
  if (col.key !== ARCHIVE.key) return readColumnNow(tasksDir, col)
  let dirMtime
  try { dirMtime = statSync(join(tasksDir, col.dir)).mtimeMs } catch { return [] }
  const hit = archiveCache.get(tasksDir)
  if (hit && hit.dirMtime === dirMtime && Date.now() - hit.at < ARCHIVE_TTL_MS) return structuredClone(hit.cards)
  const cards = readColumnNow(tasksDir, col)
  archiveCache.set(tasksDir, { dirMtime, at: Date.now(), cards })
  return structuredClone(cards)
}

function readColumnNow(tasksDir, col) {
  const dir = join(tasksDir, col.dir)
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith('.md') && !NOT_A_CARD.test(f))
    .map((f) => {
      try {
        return parseCard(join(dir, f), col.key)
      } catch {
        return null // a file mid-write; the next watch event will pick it up
      }
    })
    .filter(Boolean)
    .sort((a, b) => b.priority - a.priority || a.id.localeCompare(b.id))
}

// A parked card is one an agent has already declared unresolvable without the
// operator (`hkb park`). The auto-manager sweep skips it, so a card that needs a
// credential or a taste call is not re-read every 15 minutes forever. Clearing the
// marker is the operator's act — edit or move the card and the sweep sees it again.
export const isParked = (card) => /\*\*Parked\*\*/.test(readFileSync(card.path, 'utf8'))

// Full board snapshot: { planning: [...], planned: [...], ..., archive: [...] }
export function readBoard(tasksDir) {
  const board = {}
  for (const col of ALL) board[col.key] = readColumn(tasksDir, col)
  return board
}

// Ids come from filenames, and real repos reuse numbers over time — an archived
// T-06 and a live T-06 can genuinely coexist. Archive never wins, and a tie
// between two live cards is an error rather than a coin flip, because the caller
// is usually about to move one of them.
export function findCard(tasksDir, cardId) {
  const id = String(cardId).toUpperCase()
  const live = ALL.filter((col) => col.key !== ARCHIVE.key).flatMap((col) => readColumn(tasksDir, col)).filter((c) => c.id === id)
  const all = live.length ? live : readColumn(tasksDir, ARCHIVE).filter((c) => c.id === id)
  if (!all.length) throw new Error(`unknown card: ${cardId}`)

  if (live.length > 1) {
    if (live.length === 2 && mergeLateCopy(tasksDir, id, live)) return findCard(tasksDir, id)
    throw Object.assign(new Error(`${id} is ambiguous — ${live.map((c) => `${c.column}/${c.file}`).join(' and ')}`), { ambiguous: id })
  }
  return live[0] ?? all[0]
}

// Tradeflow T-42: a live agent wrote its result to the lane path the board had just
// moved the card out of, recreating the file there. When the last transition went
// A -> B, both copies share a file name and the A copy was written after that move,
// the A copy is that late write: its ## sections the B copy lacks are appended to B
// (a later same-named section wins in briefs), and the file is kept in .stray/.
function mergeLateCopy(tasksDir, id, copies) {
  const move = lastTransition(tasksDir, id)
  const late = copies.find((c) => c.column === move?.from), current = copies.find((c) => c.column === move?.to)
  if (!late || !current || late.file !== current.file || statSync(late.path).mtimeMs < Date.parse(move.at)) return false
  const lateText = readFileSync(late.path, 'utf8'), text = readFileSync(current.path, 'utf8')
  // Current feedback is the board's own note; the late copy's is the one it replaced.
  const added = lateText.split(/(?=^## )/m).map((s) => s.trim()).filter((s) => s.startsWith('## ') && !s.startsWith('## Current feedback') && !text.includes(s))
  appendHistory(tasksDir, id, { event: 'late-copy-merged', from: late.column, text: lateText })
  if (added.length) writeFileSync(current.path, `${text.trimEnd()}\n\n${added.join('\n\n')}\n`)
  mkdirSync(join(tasksDir, '.stray'), { recursive: true })
  renameSync(late.path, join(tasksDir, '.stray', `${Date.now()}-${late.column}-${late.file}`))
  return true
}

// Move a card between columns. This IS the state change — there is nothing else to update.
export function moveCard(tasksDir, cardId, toKey, options = {}) {
  // Issues is retired (operator 2026-09-25): anything aimed at it goes to Planning.
  if (toKey === 'issues') toKey = 'planning'
  let col = columnByKey(toKey)
  if (!col) throw new Error(`unknown column: ${toKey}`)

  const card = options.sourcePath
    ? Object.values(readBoard(tasksDir)).flat().find(c => c.path === options.sourcePath)
    : findCard(tasksDir, cardId)
  if (!card) throw new Error(`unknown card source: ${options.sourcePath}`)
  if (card.column === toKey) return card
  // Completed means "built, ready to integrate". Review runs after integration,
  // so Auto-review cards need only the Builder PASS here.
  if (toKey === 'completed' && card.cardOwned && !card.trivial && !card.reviewPassed && !hasBuilderPass(card)) {
    throw new Error(`${card.id} requires Builder PASS before Completed`)
  }
  if (card.cardOwned && ['planned', 'queue'].includes(toKey)) validatePlan(readFileSync(card.path, 'utf8'), { requireReadiness: !!options.plannerAssignment, workspace: options.planWorkspace, sharedFiles: options.sharedFiles })
  if (card.column === 'archive' && toKey !== 'archive') {
    // Only reachable when every copy of the id is archived; moving one back out
    // silently is more surprising than refusing.
    throw new Error(`${card.id} only exists in archive (${card.file}) — move it by hand if you meant that`)
  }
  if (toKey === 'archive' && !options.operatorArchive && !canArchive(card)) {
    throw new Error(`${card.id} is a mission card and needs Reviewer evidence plus Review verdict: PASS before archive`)
  }

  const text = readFileSync(card.path, 'utf8')
  if (toKey === 'archive' && card.audit) {
    const error = auditArchiveError(text, id => id !== card.id && !!findCard(tasksDir, id))
    if (error) throw new Error(error)
  }
  const transition = recoveryTransition(text, card.column, toKey, options)
  toKey = transition.to
  col = columnByKey(toKey)
  const dest = join(tasksDir, col.dir)
  mkdirSync(dest, { recursive: true })
  let target = join(dest, card.file)
  if (options.sourcePath && existsSync(target)) {
    const ext = extname(card.file)
    const stem = card.file.slice(0, -ext.length)
    let copy = 2
    do { target = join(dest, `${stem}-duplicate-${copy++}${ext}`) } while (existsSync(target))
  }
  if (existsSync(target)) throw new Error(`already exists in ${toKey}: ${card.file}`)

  appendHistory(tasksDir, card.id, { event: 'transition', from: card.column, to: toKey, text, ...(options.operatorArchive && toKey === 'archive' ? { note: 'Archived by operator from board without independent review' } : {}) })
  if (transition.text !== text) writeFileSync(card.path, transition.text)
  renameSync(card.path, target)
  return { ...card, column: toKey, path: target }
}

function constraintsFor(tasksDir, category) {
  if (!existsSync(join(tasksDir, 'PROJECT-CONSTRAINTS.md'))) return '<!-- Optional; populated only when this project has relevant constraints. -->'
  return projectConstraints(tasksDir, category) || '<!-- No project-specific constraints for this category. -->'
}

// Legacy cards (migrated from TASKS.md, not card-owned) have no Planner path, so they
// sat in Planning until the stall watchdog sent them to Owner (Healthypets T-01..03).
// Convert in place to the card-owned template: same file, ID and title; the authored
// body (before the first --- board-event separator, headings demoted) becomes the
// Approved brief. The full original text is saved to card history first.
export function convertLegacyCard(tasksDir, card, now = new Date()) {
  const original = readFileSync(card.path, 'utf8')
  if (card.audit || /^\*\*Workflow:\*\* card-owned$/m.test(original)) return card
  const entry = appendHistory(tasksDir, card.id, { event: 'legacy-conversion-source', sourcePath: card.path, sourceHash: createHash('sha256').update(original).digest('hex'), text: original })
  const lines = original.split(/\r?\n/)
  const body = lines.slice(lines.findIndex(line => HEADING.test(line)) + 1).join('\n')
    .split(/^---[ \t]*$/m)[0].replace(/^#{1,2}(?= )/gm, '###').trim()
  const brief = `${body}\n\nConverted from a legacy card on ${now.toISOString()}; the original text, including its board history, is saved in ${historyPath(tasksDir, card.id).replaceAll('\\', '/')} (entry ${entry.id}).`
  const values = { ID: card.id, TITLE: card.title, CREATED: original.match(/^\*\*Created:\*\*\s*(\S+)/m)?.[1] || now.toISOString(), CATEGORY: card.category, WORKSPACE: card.workspace || '.', MISSION: '', BRIEF: brief, PROJECT_CONSTRAINTS: constraintsFor(tasksDir, card.category) }
  const text = readFileSync(TEMPLATE, 'utf8')
    .replace(/\{\{(ID|TITLE|CREATED|CATEGORY|WORKSPACE|MISSION|BRIEF|PROJECT_CONSTRAINTS)\}\}/g, (_, key) => values[key])
    .replace(/^\*\*Priority\*\* \d+\/10$/m, `**Priority** ${card.priority || 5}/10${card.blockedBy?.length ? `\n**Blocked by:** ${card.blockedBy.join(', ')}` : ''}`)
  const temp = `${card.path}.convert-${process.pid}.tmp`
  writeFileSync(temp, text, { flag: 'wx' })
  renameSync(temp, card.path)
  return parseCard(card.path, card.column)
}

// Blocked-by prerequisites not yet landed: Completed and integrated, or Archive.
export function unmetBlockers(card, board, integrated = {}) {
  const live = Object.entries(board).filter(([key]) => key !== 'archive').flatMap(([, cards]) => cards)
  return (card.blockedBy || []).filter((id) => {
    const alive = live.filter((c) => c.id === id)
    const archived = board.archive.filter((c) => c.id === id)
    if (!alive.length && archived.length === 1) return false
    // Review now happens after integration, so an integrated card in Review has already landed.
    return !(alive.length === 1 && archived.length === 0 && ['completed', 'review'].includes(alive[0].column) && integrated[id]?.state === 'integrated')
  })
}
// Unmet prerequisites that are still live cards: an allowed wait (TF44). A
// prerequisite missing from the board can never land, so that is not a wait.
export function waitingOnPrerequisites(card, board, integrated = {}) {
  const unmet = unmetBlockers(card, board, integrated)
  const live = new Set(Object.entries(board).filter(([key]) => key !== 'archive').flatMap(([, cards]) => cards.map((c) => c.id)))
  return unmet.length && unmet.every((id) => live.has(id)) ? unmet : []
}

// `prefix` is the project's card prefix (board.config.json cardPrefixes); without
// one the project keeps issuing legacy T- ids.
export function createCard(tasksDir, { title, brief, category = 'code', workspace = '.', audit = '', tools = '', mission = '', prefix = 'T-', priority, blockedBy, now = new Date() }) {
  if (typeof title !== 'string' || !title.trim() || title.length > 200 || /[\r\n]/.test(title)) throw new Error('A single-line title of at most 200 characters is required')
  if (typeof brief !== 'string' || !brief.trim() || brief.length > 50000) throw new Error('An approved brief of at most 50000 characters is required')
  if (typeof mission !== 'string' || /[\r\n]/.test(mission)) throw new Error('Invalid mission')
  category = String(category).toLowerCase()
  if (!CATEGORIES.includes(category)) throw new Error(`Category must be one of: ${CATEGORIES.join(', ')}`)
  workspace = String(workspace).replace(/\\/g, '/').trim() || '.'
  if (/^[A-Za-z]:|^\/|(^|\/)\.\.(\/|$)/.test(workspace)) throw new Error('Workspace must be a project-relative path')
  audit = String(audit).toLowerCase()
  if (audit && !AUDITS.includes(audit)) throw new Error(`Audit must be one of: ${AUDITS.join(', ')}`)
  if (audit === 'general' && !String(tools ?? '').trim()) tools = '- chrome-devtools (headless isolated browser: screenshots, DOM measurements, console and network)'
  if (audit && (typeof tools !== 'string' || !tools.trim())) throw new Error('Audit cards require exact tools/MCPs')
  if (priority !== undefined) checkPriority(priority)
  const board = readBoard(tasksDir)
  const id = nextCardId(prefix, Object.values(board).flat().map(c => c.id))
  if (blockedBy !== undefined) blockedBy = checkBlockers(board, id, blockedBy, 'blockedBy')
  const dir = join(tasksDir, audit ? 'review' : 'planning')
  mkdirSync(dir, { recursive: true })
  const path = join(dir, audit ? `${id}-audit-${audit}.md` : `${id}-approved-job.md`)
  const template = readFileSync(audit ? AUDIT_TEMPLATES[audit] : TEMPLATE, 'utf8')
  // The project copy is a reference; creation always uses the board's canonical template.
  if (!audit) writeFileSync(join(tasksDir, 'TASK-TEMPLATE.md'), template)
  const values = { ID: id, TITLE: title.trim(), CREATED: now.toISOString(), CATEGORY: category, WORKSPACE: workspace, AUDIT: audit, TOOLS: tools.trim(), MISSION: mission ? `**Mission:** ${mission}` : '', BRIEF: brief.trim(), PROJECT_CONSTRAINTS: constraintsFor(tasksDir, category) }
  let text = template.replace(/\{\{(ID|TITLE|CREATED|CATEGORY|WORKSPACE|AUDIT|TOOLS|MISSION|BRIEF|PROJECT_CONSTRAINTS)\}\}/g, (_, key) => values[key])
  if (priority !== undefined) text = withPriority(text, priority)
  if (blockedBy?.length) text = withBlockers(text, blockedBy)
  writeFileSync(path, text, { flag: 'wx' })
  return parseCard(path, audit ? 'review' : 'planning')
}

// Whether an agent for this card needs the browser MCPs (chrome-devtools, playwright,
// computer-use). UI cards and any card naming browser work get them; others start lean.
export function needsBrowser(card) {
  if (card.category === 'ui' || card.audit) return true
  try { return /chrome-devtools|playwright|browser|screenshot|viewport|lighthouse|visual|\b\d{3,4}\s?px\b/i.test(readFileSync(card.path, 'utf8')) } catch { return true }
}
